#lang racket
(require "another-a-mini-kanren/another-a-mini-kanren.rkt")

(fresh (h)
       (run* (h) (all (== h (list
                          (list 'a (_))
                          (list 'b (_))
                          (list 'c (_))
                          ))
                      (any (memo (list 'a 't) h)
                           (memo (list 'a 'f) h))
                      (any (memo (list 'b 't) h)
                           (memo (list 'b 'f) h))
                      (any (memo (list 'c 't) h)
                           (memo (list 'c 'f) h))
                      (any (all (memo (list 'a 't) h)
                                (memo (list 'b 'f) h))
                           (all (memo (list 'a 'f) h)
                                (memo (list 'b 't) h)))
                      (any (all (memo (list 'b 't) h)
                                (any (all (memo (list 'a 't) h)
                                          (memo (list 'c 't) h))
                                     (all (memo (list 'a 'f) h)
                                          (memo (list 'c 'f) h))))
                           (all (memo (list 'b 'f) h)
                                (any (all (any (memo (list 'a 'f) h)
                                               (memo (list 'c 'f) h))
                                          (any (memo (list 'a 't) h)
                                               (memo (list 'c 't) h))))))
                      )))